### ISSUE TITLE
plugin not found: miller_csv

### ISSUE THREAD

**Issue by paletochen** [Reledia/miller.yazi#2]
Hi,
I tried to install this plugin without success.

When following the instructions exactly:
- Clone repo and rename folder from `miller.yazi` to `miller_csv` under `~/.config/yazi/plugins`
- Add the configuration in `yazi.toml`

and when i try to preview a csv file I get a black result on the preview window and the following error in `yazi.log`

```
  [2m2024-02-15T08:02:01.199140Z[0m [31mERROR[0m [1;31myazi_plugin::isolate::peek[0m[31m: [31mplugin not found: miller_csv[0m
    [2;3mat[0m /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/yazi-plugin-0.2.3/src/isolate/peek.rs:50

  [2m2024-02-15T08:02:01.661546Z[0m [31mERROR[0m [1;31myazi_plugin::isolate::peek[0m[31m: [31mplugin not found: miller_csv[0m
    [2;3mat[0m /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/yazi-plugin-0.2.3/src/isolate/peek.rs:50
```

I tried other options which also didn't work:
- kept git folder within plugins as `miller.yazi`
- changed in `yazi.toml` the exec command to `mlr` as it seems in `init.lua` file the command to run is `mlr`
- ... and maybe some other combinations with the above.

Any help to make this work will be appreciated.
Thanks

**Comment by sxyazi** [comment]
It seems that the document is wrong, it should be `{ mime = "text/csv", exec = "miller"}` in your `yazi.toml`, and place this plugin at `~/.config/yazi/plugins/miller.yazi`

**Comment by Reledia** [comment]
My bad, I changed the title and forgot to update the README. It's now updated

**Comment by paletochen** [comment]
Thanks, it works now :)
